@extends('nav')

@section('container')
	<h2 style="text-align: center; padding-top: 40px; font-family: verdana; font-weight: bolder;">{{ $judul }}</h2>
	<center><img src="foto/utm.jpg" style="width: 50%;"></center><br>
	<h3 style="text-align: center; font-family: fantasy;">{{$utm}}</h3>
	<p style="text-align: justify; font-family: initial;">Universitas Trunojoyo Madura (UTM) atau dikenal juga UNIJOYO dulunya bernama Universitas Bangkalan Madura (UNIBANG) terletak di Kecamatan Kamal, Bangkalan Madura. Berdiri pada tahun 1981 dengan nama UNIBANG melalui Yayasan Pendidikan Kyai Lemah Dhuwur MKGR Bangkalan yang kemudian diresmikan oleh Presiden Abdurrahman Wachid menjadi Universitas Trunojoyo Madura sebagai Perguruan Tinggi Negeri pada tahun 2001 berdasarkan keputusan Presiden RI No. 85 Tahun 2001 pada tanggal 5 Juli 2001. UTM juga sudah terakreditasi B berdasarkan no 417/SK/BAN-PT/Akred/PT/XI/2019. Moto Universitas Trunojoyo Madura yakni UTM APIK (Amanah, Peduli, Kreatif). </p>
	<p style="text-align: justify; font-family: initial;">Terdapat tujuh fakultas di Universitas Trunojoyo Madura yang menyelenggarakan beberapa program studi diploma, sarjana, dan magister. Fakultas tersebut yakni Fakultas Hukum, Fakultas Ekonomi dan Bisnis, Fakultas Pertanian, Fakultas Teknik, Fakultas Ilmu Sosial dan Budaya, Fakultas Ilmu Pendidikan, dan Fakultas Keislaman. Prestasi mahasiswanya juga mencapai tingkat nasional bahkan internasional. Salah satunya adalah Ach Zahid yang mencetak rekor MURI penjahitan dan pembentangan bendera Merah Putih terpanjang bersama dengan mahasiswa UTM pada HUT ke-73 RI. Fasilitas di UTM sudah termasuk lengkap, terdapat asrama mahasiswa, gedung olahraga, laboratorium, masjid, gedung serba guna, perpustakaan, koperasi mahasiswa, dan beberapa fasilitas lain. </p>
	<h3 style="text-align: center; font-family: fantasy;">{{$informatika}}</h3>
	<p style="text-align: justify; font-family: initial;">Teknik Informatika merupakan salah satu program studi yang ada di Universitas Trunojoyo Madura di bawah naungan Jurusan Teknik Informatika Fakultas Teknik. Teknik Informatika satu jurusan dengan program studi Sistem Informasi. Saat ini koordinator prodinya adalah ibu Fika Hastarita Rachman, ST., M.Eng. Dalam program studi Teknik Informatika terdapat pula Himpunan Mahasiswa Teknik Informatika yang biasa di kenal dengan HIMATIF. Program studi ini memiliki empat bidang minat yaitu sistem terditribusi, sistem informasi dan rekayasa perangkat lunak, komputasi dan sistem cerdas, serta sistem multimedia.</p>
	<h5 style="font-family: cursive;">Sistem Terdistribusi</h5>
	<p style="text-align: justify; font-family: initial;">Untuk sistem terdistribusi menekankan untuk memahami dan menguasai prinsip networking, kemampuan merancang dan mengimplementasikan jaringan, memahami dan menguasai prinsip dasar web dan teknologi internet, mampu mengimplementasikan aplikasi perangkat bergerak, memahami sistem temu kembali informasi, dan memiliki keahlian meneliti sesuai metodologi penelitian. Lulusannya di harapkan mampu berkontribusi sebagai network engineer, web engineer, mobile app engineer, maupun peneliti</p>
	<h5 style="font-family: cursive;">Sistem Informasi dan Rekayasa Perangkat Lunak</h5>
	<p style="text-align: justify; font-family: initial;">Minat ini menekankan pada pengerjaan projek planning, analisa desain dan sistem, implementasi sistem, memberikan problem solving berbasis ICT, mengembangkan penelitian di bidang RPL, serta mengimplementasikan produk teknologi informasi. Lulusan diharapkan mampu berkontribusi sebagai consultant engineer, software engineer, researcher, dan technical engineer.</p>
	<h5 style="font-family: cursive;">Komputasi dan Sistem Cerdas</h5>
	<p style="text-align: justify; font-family: initial;">Bidang minat komputasi dan sistem cerdas menekankan pada kemampuan dalam melakukan penelitian menggunakan metodologi penelitian, kemampuan untuk menyampaikan pemikiran ilmiah baik secara lisan maupun tulisan, serta kemampuan dalam mengidentifikasi, mendayagunakan, dan mengevaluasi pengembangan sistem berbasis algoritma cerdas. Lulusan diharapkan dapat berkontribusi sebagai peneliti, akademisi, dosen, analis di bidang kecerdasan buatan, dan konsultasn di bidang kecerdasan buatan.</p>
	<h5 style="font-family: cursive;">Sistem Multimedia</h5>
	<p style="text-align: justify; font-family: initial;">Bidang ini menekankan pada kemampuan dalam penguasaan dasar konsep dan keahlian pemrograman, kemampuan merancang dan mengimplementasikan sistem, serta mengintegrasikan hardware dan software, serta memahami berbagai jenis objek riset multimedia untuk diaplikasikan. Lulusan diharapkan mampu berkontribusi sebagai ICT enterpreneur, ICT engineering, researcher dan lecturer. </p>
	<h3 style="text-align: center; font-family: fantasy;">{{$cerita}}</h3>
	<p style="text-align: justify; font-family: initial;">Awalnya tidak pernah terpikir untuk masuk di program studi Teknik Informatika Universitas Trunojoyo Madura. Bahkan untuk melanjutkan pendidikan di UTM pun tidak pernah terfikir. Dulu saat pendaftaran untuk melanjutkan pedidikan saya mendaftar melalui 3 jalur yang ketiganya menggunakan nilai rapor. Untuk jalur yang pertama SNMPN jalur untuk mendaftar politeknik negeri, saya mendaftar di Politeknik Negeri Malang yang merupakan salah satu kampus impian saya untuk melanjutkan pendidikan saya. Kemudian jalur kedua SPAN-PTKIN jalur untuk mendaftar di universitas negeri islam dan saya mendaftar di dua universitas yakni Universitas Islam Negeri Surabaya dan Universitas Islam Negeri Maulana Malik Ibrahim Malang. Dan yang terakhir SNMPTN saya mendaftar di Universitas Trunojoyo Madura untuk program studi teknik informatika dan program studi teknik industri atas saran yang diberikan oleh salah satu guru saya karena saya memang tidak ingin melanjutkan pendidikan di jenjang Universitas.</p>
	<p style="text-align: justify; font-family: initial;">Pada saat pengumuman SNMPN saya sangat berharap untuk bisa diterima, namun hasilnya saya tidak diterima. Tidak lama setelah itu pengumuman SNMPTN saya tidak berharap untuk diterima karena saya ingin mencoba SBMPTN untuk melanjutkan di PTN di luar Jawa Timur dan SBMPN untuk tetap berkuliah di politeknik, namun hasilnya saya malah diterima di prodi teknik informatika Universitas Trunojoyo Madura. Dan akhirnya saya memutuskan untuk memilih teknik informatika UTM setelah melalui banyak pertimbangan. </p>
@endsection

